apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi
  labels:
    app: gatewayapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayapi
  template:
    metadata:
      labels:
        app: gatewayapi
    spec:
      containers:
        - name: gatewayapi
          image: b1tech/gatewayapi:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
