{
 "title": "API-Cadastro-Dashboard",
 "description": "Dashboard de metricas do projeto API-Cadastro fiap6NET ",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Número total de requisições",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (http_requests_received_total{job=\"gatewayapi\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime do sistema",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória RAM usada (%)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{job=\"gatewayapi\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"gatewayapi\"}[1m]) \r\n/\r\nrate(http_request_duration_seconds_count{job=\"gatewayapi\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Disco (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m]) + rate(node_disk_written_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tráfego de Rede (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}